### PR TITLE
API Deployment

### PR DESCRIPTION
**Pull request by sasalx**
Finally, I found a way to deploy API without exposing keys. As we tested before, you have to put it to the actual application to test it.

API Adress: `https://quela-api.herokuapp.com/`

After testing, let me know if there is a problem. If not you can merge to master.

---

### CODE REVIEW

**Comment by kondanta** [comment]
Well, direct usage of the URL does not work. There's no documentation, so I don't know how to use it as well. Plus you're gonna write tests you might consider adding Travis like CI/CD tool to run automated tests and test deployment. I'll accept or hang this PR depending on your answer.

Cheers :smiley:

**Comment by sasalx** [comment]
Yes, the direct link is not working. As I said, it's for application use. On the other hand, I believe you don't need documentation since all you have to do is replace the API link with localhost. And of course, you should test the app to see if the API is working correctly.

For running it locally, I will provide the env file after working on the tests.

**Comment by kondanta** [comment]
```
E/flutter ( 4436): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: TimeoutException after 0:00:10.000000: Future not completed
E/flutter ( 4436): #0      DashboardBloc._handleApiCall (package:quela/bloc/patient_dashboard_bloc.dart:26:34)
E/flutter ( 4436): <asynchronous suspension>
E/flutter ( 4436): #1      new DashboardBloc (package:quela/bloc/patient_dashboard_bloc.dart:14:5)
E/flutter ( 4436): #2      PatientDashboardBuilder.build (package:quela/pages/patient/dashboard_builder.dart:12:13)
E/flutter ( 4436): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
E/flutter ( 4436): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
E/flutter ( 4436): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 4436): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter ( 4436): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter ( 4436): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 4436): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 4436): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter ( 4436): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 4436): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 4436): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter ( 4436): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 4436): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 4436): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 4436): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 4436): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter ( 4436): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter ( 4436): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 4436): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 4436): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 4436): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 4436): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter ( 4436): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter ( 4436): #26     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
E/flutter ( 4436): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 4436): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 4436): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 4436): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 4436): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter ( 4436): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter ( 4436): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter ( 4436): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 4436): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 4436): #36     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1030:36)
E/flutter ( 4436): #37     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1015:20)
E/flutter ( 4436): #38     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
E/flutter ( 4436): #39     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1008:11)
E/flutter ( 4436): #40     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
E/flutter ( 4436): #41     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1728:58)
E/flutter ( 4436): #42     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
E/flutter ( 4436): #43     RenderObject.invokeLayoutCallback (package:flutter/src/renderi
```
That means url is not responding tot he API requests.

Quick edit: It works now. I'll be accepting this PR after you explaining why has that happened.

**Comment by sasalx** [comment]
If I have to guess, since we are using the free version of Heroku the server is not working 7/24. When we send a request to the server, it tries to boot up and that takes time thus resulting in the error.

**Review by kondanta — COMMENTED** [review]
aight, merged! :+1:

**Pull request merged**
